name: Yew Styles

on:
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install rustfmt
        run: rustup component add rustfmt
      - name: install clippy
        run: rustup component add clippy
      - name: install stable
        run: rustup install stable
      - name: add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: download geckodriver
        run: curl --retry 5 -LO https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
      - name: uncompress geckodriver
        run: tar -xzf geckodriver-v0.27.0-linux64.tar.gz
          echo "::add-path::$HOME/geckodriver"
      - name: execute CI
        run: GECKODRIVER=$(pwd)/geckodriver ./ci/run_checks.sh
